# This is a basic workflow to help you get started with Actions

name: Spring Boot CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 11 
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## grading caching start
      - name: Grading caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}
          restore-keys: |
            ${{ runner.os }}-gradle-
          
      ## create application-dev.properties
      - name: create application-dev.properties
        run: |
          cd ./src/main/resources
          touch ./application-dev.properties
          echo "{{ secrets.DEV_DB_SCRET}}" > ./application-dev.properties
        shell: bash
        
      ## Build with Gradle
      - name: build gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test    
        shell: bash
        
        
